// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg1v0G06QwEB0Q_nxN-Nr-mDKDq51x8Nw',
    appId: '1:1007453976252:web:286cfd3b478c0c253042b9',
    messagingSenderId: '1007453976252',
    projectId: 'professional-blog-a388a',
    authDomain: 'professional-blog-a388a.firebaseapp.com',
    storageBucket: 'professional-blog-a388a.appspot.com',
    measurementId: 'G-6S2DCPBEQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11X3AWCbwHMgrzBtzNublDqGJtVyDieY',
    appId: '1:1007453976252:android:8b2f7871b4baae9c3042b9',
    messagingSenderId: '1007453976252',
    projectId: 'professional-blog-a388a',
    storageBucket: 'professional-blog-a388a.appspot.com',
  );
}
